Phase2WebAPI/Phase2.API/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Phase2.API.Areas.HelpPage.ModelDescriptions;
using Phase2.API.Areas.HelpPage.Models;

namespace Phase2.API.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

Phase2WebAPI/Phase2.API/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Phase2WebAPI.Models;
using Phase2.API.Models;
using System.Web.Helpers;
using System.Web.Security;

namespace Phase2.API.Controllers
{
    public class LoginController : Controller
    {

        private Phase2APIContext db = new Phase2APIContext();


        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Phase2WebAPI.Models.User User)
        {

            if (IsValid(User.Email, User.Password))
            {
                User currentUser = db.Users.FirstOrDefault(u => u.Email == User.Email);
                if (currentUser != null) Session["CurrentUserId"] = currentUser.Id;

                FormsAuthentication.SetAuthCookie(User.Email, true);
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "Login information is incorrect.");
            return View(User);
        }

        [Authorize]
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();

            return RedirectToAction("Index", "Home");
        }

        private bool IsValid(string userName, string password)
        {
            bool IsValid = false;

            var user = db.Users.FirstOrDefault(u => u.Email.Equals(userName));

            if (user != null && Crypto.VerifyHashedPassword(user.Password, password))
            {
                IsValid = true;
            }
            return IsValid;
        }
    }
}

Phase2WebAPI/Phase2.API/Controllers/ManageUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Phase2WebAPI.Models;
using Phase2.API.Models;
using System.Web.Helpers;
using System.Net;
using System.Data.Entity.Migrations;

namespace Phase2.API.Controllers
{
    public class ManageUsersController : Controller
    {

        private Phase2APIContext db = new Phase2APIContext();

        // GET: ManageUsers
        public ActionResult UserManagement()
        {
            return View(db.Users.ToList());
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Phase2WebAPI.Models.User user)
        {
            bool userNameInUse = db.Users.Any(u => u.Email.Equals(user.Email));
            if (userNameInUse == true)
            {
                ModelState.AddModelError("", "Username in use.");


            }
            else
            {
                if(ModelState.IsValid)
                {
                    user.Password = Crypto.HashPassword(user.Password);
                    db.Users.Add(user);
                    db.SaveChanges();
                    return RedirectToAction("UserManagement");
                }
            }
            return View(user);
        }

        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,Password")] Phase2WebAPI.Models.User user)
        {
          
                
            try
            {
                if (ModelState.IsValid)
                {
                    user.Password = Crypto.HashPassword(user.Password);
                    //input api key here
                    db.Users.AddOrUpdate(user);
                    db.SaveChanges();
                    return RedirectToAction("UserManagement");
                }
                return View(user);
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting
                        // the current instance as InnerException
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }

        }

        private bool IsValid(string userName, string password)
        {
            bool IsValid = false;

            var user = db.Users.FirstOrDefault(u => u.Email.Equals(userName));

            if (user != null && Crypto.VerifyHashedPassword(user.Password, password))
            {
                IsValid = true;
            }
            return IsValid;
        }

        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("UserManagement");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Phase2WebAPI/Phase2.API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("TestingPage", "TestingPage", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("SPA", "index", "SPA", new { area = "" }, null)</li>
                    @if (Request.IsAuthenticated)
                    {

                        <li>@Html.ActionLink("Manage Users", "UserManagement", "ManageUsers", new { area = "" }, null)</li>

                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Request.IsAuthenticated)
                    {

                        <li>@Html.ActionLink("LogOut", "LogOut", "Login", new { area = "" }, null)</li>

                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Login", new { area = "" }, null)</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>